### ISSUE TITLE
Perhaps naming the token "777" is confusing?

### ISSUE THREAD

**Issue by amin1419** [cardano-foundation/CIPs#175] opened 2021-12-15 01:22 UTC
Perhaps naming the token "777" is confusing? Again, it's an "easily recognizable" indicator as to the purpose of this token being "royalty control" over a target. Also because the implementation is different from the original CIP-0027 it seems like naming it is important rather than no name...and we implement a smartcontract for this since it needs to be "findable" given a token with a different policy ID (but shared policy hash).

Although it may not need a name standard, it could theoretically be called anything since a secondary market searches the smartcontract address for a matching datum and only cares about this token's policy ID when validating ownership and comparing hashes, policy script outcomes, etc.

_Originally posted by @ullamonster in https://github.com/cardano-foundation/CIPs/issues/168#issuecomment-988497726_

**Comment by rphair** [comment] 2021-12-15 03:47
@amin1419 if you would like to develop @ullamonster 's comment further... enough to consider as an issue in its own right... then please do so here.

Otherwise I'd suggest we close this ticket because the point above has already been made in #168 where it's been viewed & recognised already in the overall discussion.

**Comment by rphair** [comment] 2021-12-18 16:37
Closing as duplicate of https://github.com/cardano-foundation/CIPs/issues/168.

**Closed by rphair** 2021-12-18 16:37 UTC
